import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider, createTheme } from "@mantine/core";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const theme = createTheme({
  primaryColor: "violet",
  fontFamily: inter.style.fontFamily,
  headings: {
    fontFamily: inter.style.fontFamily,
    sizes: {
      h1: { fontSize: "3.3rem", fontWeight: 900, lineHeight: 1.2 },
      h2: { fontSize: "2.4rem", fontWeight: 800 },
      h3: { fontSize: "1.75rem", fontWeight: 700 },
    },
  },
  colors: {
    dark: [
      "#E7ECF5", // 0 - off-white for text
      "#dfe3ea", // 1
      "#c7ccd6", // 2
      "#9aa3b2", // 3
      "#A6B0C2", // 4 - muted/secondary text
      "#4b5567", // 5
      "#2a3342", // 6
      "#161c27", // 7
      "#0B1220", // 8 - main background, deep inky blue black
      "#05070d"  // 9 - deepest, for surfaces/borders
    ],
  },
  black: "#0B1220",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-mantine-color-scheme="dark">
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body className={inter.className}>
        <MantineProvider
          theme={theme}
          defaultColorScheme="dark"
          styles={{
            body: {
              backgroundColor: theme.colors.dark[8],
              color: theme.colors.dark[0],
            },
          }}
        >
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
